name: feather
description: A flutter utility library with re-frame esk features
version: 0.2.0
author: AXRS <xander@axrs.io>
homepage: https://github.com/axrs/feather

dependencies:
  flutter:
    sdk: flutter
  flutter_stream_friends: ^0.8.0
  rxdart: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev <3.0.0"
